module.exports = {
  currencies: {
    MXN: 'mxn',
    BTC: 'btc',
    ETH: 'eth',
    XRP: 'xrp',
    LTC: 'ltc',
  },
  exchanges: {
    BTC_ETH: 'btc_eth',
    BTC_XRP: 'btc_xrp',
    BTC_LTC: 'btc_ltc',
    BTC_MXN: 'btc_mxn',
    ETH_BTC: 'eth_btc',
    ETH_XRP: 'eth_xrp',
    ETH_LTC: 'eth_ltc',
    ETH_MXN: 'eth_mxn',
    XRP_BTC: 'xrp_btc',
    XRP_ETH: 'xrp_eth',
    XRP_LTC: 'xrp_ltc',
    XRP_MXN: 'xrp_mxn',
    LTC_BTH: 'ltc_btc',
    LTC_ETH: 'ltc_eth',
    LTC_XRP: 'ltc_xrp',
    LTC_MXN: 'ltc_mxn',
  },
};
